---
title: "Final Project"
author: "Garrett Rolph"
date: "April 21, 2020"
output: html_document
---

## Background
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(readxl)
library(janitor)
library(ggplot2)
library(haven)
library(googlesheets4)
library(googlesheets)
library(pdftools)
library(snakecase)
library(zoo)
options(scipen = 999)
```


```{r Alabama}
AL_outcomes <- read_excel("States/Alabama/2018-2019 Report Card Profile.xlsx", skip = 4)
AL_summary <- read_excel("States/Alabama/2017-2018 Summative Assessment Results (Data Center).xlsx") %>% clean_names() 
```

```{r Arkansas}
AR_ACT <- read_excel("States/Arkansas/G11ACT_Summary_2019.xlsx") %>% clean_names()
```

```{r California}
CA_SAT <- read_excel("States/California/sat19.xls") %>% clean_names()
CA_ACT <- read_excel("States/California/act19.xls") %>% clean_names() 
CA_financial <- read_excel("States/California/j90summary1819.xlsx", skip = 167) %>% 
  select(2,6) %>% 
  rename(district = ...2,
         average_salary = ...6) %>% 
  na.omit() %>% 
  mutate(average_salary = str_replace(average_salary, "N/A", NA_character_),
         average_salary = 
           as.numeric(as.character(str_replace(average_salary, "Average", NA_character_)))) %>% 
  na.omit() %>% 
  mutate(average_CA_salary = mean(average_salary))

CA_joined <- CA_SAT %>% 
  full_join(CA_financial, by = c("dname" = "district"))
```

```{r Colorado, message = FALSE}
CO_SAT <- read_excel("States/Colorado/2019 PSAT and SAT Disaggregated District and School Achievement Results.xlsx", skip = 10) %>% 
  clean_names()

CO_agg_SAT <- read_excel("States/Colorado/2019 PSAT SAT District and School Achievement Results.xlsx", skip = 10) %>% 
  clean_names()

CO_principal_sals <- read_excel("States/Colorado/2018-19 Average Principal and Asst Principal Salary by District.xlsx", skip = 3) %>% 
  clean_names() 

CO_supt_sals <- read_excel("States/Colorado/2018-19 Average Superintendent Salary by District.xlsx", skip = 3) %>% 
  clean_names()

CO_teacher_sals <- read_excel("States/Colorado/2018-19 Average Teacher Salary by District.xlsx", skip = 3) %>% 
  clean_names() %>% 
  rename("average_salary" = "x4",
         "district_name" = "orgnazation_name")

CO_turnover <- read_excel("States/Colorado/2018-19 Personnel Turnover Rate by District and Position Categories.xlsx", skip = 3) %>% 
  clean_names()

CO_ratios <- read_excel("States/Colorado/2018-19 Student Teacher Ratios.xlsx", skip = 2) %>% 
  clean_names() 

CO_teacher_demos <- read_excel("States/Colorado/2018-19 Teachers by District, Race and Gender.xlsx", skip = 3) %>% 
  clean_names() 
```

```{r CO score vs. teacher salary}
  CO_SAT_sals <- inner_join(CO_SAT, CO_teacher_sals, 
                            by = c("district_name" = "district_name")) %>% 
  rename("average_total_salary" = "x8") %>% 
  filter(!number_of_valid_scores == "< 16") 

CO_SAT_and_salary <- CO_SAT_sals %>% 
  mutate(average_sal = str_replace_all(x6, "0", NA_character_)) %>% 
  na.omit() %>% 
  mutate(total_score_mean_score = as.numeric(as.character(total_score_mean_score)),
         average_sal = as.numeric(as.character(average_sal)))

CO_SAT_salary_image <- CO_SAT_and_salary %>%
  group_by(school_name) %>% 
  filter(test == "SAT") %>% 
  arrange(desc(total_score_mean_score)) %>% 
  ggplot(aes(total_score_mean_score, average_sal)) + geom_point(position = 'dodge') + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(method = lm, se = F) +
  labs(title = "Correlation of Colorado's SAT Scores to Teacher Salaries",
       subtitle = "Where Score is Average Total SAT Score and Salary is Average Teacher Salary",
       y = "Salary", 
       x = "Score")

CO_SAT_salary_image

CO_SAT_salary_image %>% 
  ggsave(filename = file.path("final-proj-shiny", "colorado_sat_salary.png"))
```

```{r Colorado Top 20 Math Scores}
CO_gendered_outcomes <- CO_SAT_sals %>%
  group_by(gender) %>% 
  filter(test == "SAT") %>% 
  arrange(desc(mathematics_mean_score)) %>% 
  head(40) %>%    
    mutate(school_name = factor(school_name, levels = c(
    "LIBERTY COMMON CHARTER SCHOOL", "D'EVELYN JUNIOR/SENIOR HIGH SCHOOL", "DSST: BYERS HIGH SCHOOL", "THOMAS MACLAREN STATE CHARTER SCHOOL", "FAIRVIEW HIGH SCHOOL", "THE VANGUARD SCHOOL (HIGH)", "PEAK TO PEAK CHARTER SCHOOL", "STARGATE CHARTER SCHOOL","CHERRY CREEK HIGH SCHOOL", "PROSPECT RIDGE ACADEMY",  "STEM SCHOOL HIGHLANDS RANCH", "DSST: STAPLETON HIGH SCHOOL", "JEFFERSON ACADEMY HIGH SCHOOL",  "TCA COLLEGE PATHWAYS","SKYVIEW ACADEMY","MONARCH HIGH SCHOOL","FOSSIL RIDGE HIGH SCHOOL","COLORADO EARLY COLLEGES - PARKER","ROCK CANYON HIGH SCHOOL", "EVERGREEN HIGH SCHOOL","All Schools","DENVER SCHOOL OF THE ARTS","THE CLASSICAL ACADEMY HIGH SCHOOL", "PALMER RIDGE HIGH SCHOOL", "CHEYENNE MOUNTAIN HIGH SCHOOL","CRESTED BUTTE SECONDARY SCHOOL"))) %>% 
  ggplot(aes(school_name, mathematics_mean_score, fill = gender)) + geom_col(stat = 'identity',
                                                              position = 'dodge') +
  coord_flip() +
  theme_classic() +
  labs(title = "Average Scores by Gender",
       subtitle = "Of the top 20 Schools in Colorado",
       y = "Average Math Score",
       x = "School Name") +
    theme(axis.text.x = element_text(angle = 270, hjust = 1)) +
            scale_fill_discrete(name = "Gender")

CO_gendered_outcomes

CO_gendered_outcomes %>% 
ggsave(filename = file.path("final-proj-shiny", "colorado_gender_outcome.png"))
```

```{r Connecticut, cache = TRUE}
CN_expenditures <- read_excel("States/Connecticut/CN_financial.xlsx", skip = 1) %>% 
  clean_names()

CN_expenditures <- CN_expenditures[ ,-c(3:6)] %>% 
  na.locf(., fromLast = TRUE) %>% 
  filter(type == "Total Expenditures") %>% 
  rename(amount = "x2016_17") %>% 
  mutate(CN_avg = mean(as.numeric(as.character(amount))))

CN_avg_expenditure <- CN_expenditures %>% 
  select(CN_avg) %>% 
  head(1) 

CN_teacher_demos <- read_excel("States/Connecticut/CN teacher demos.xlsx", skip = 1) %>% clean_names() %>% 
  na.locf(., fromLast = TRUE)

CN_teacher_demos <- CN_teacher_demos[ ,-c(3:10)] 

CN_SAT <- read_excel("States/Connecticut/CN SAT.xlsx", skip = 2) %>% clean_names()

CN_SAT <- CN_SAT[ , -c(3:11)] 

CN_SAT <-  data.frame(lapply(CN_SAT, function(x) {
                gsub('\\*', NA_character_, x)
             })) %>% 
  na.locf(., fromLast = TRUE) %>% 
  mutate(CN_SAT_avg = mean(as.numeric(as.character(average_score_14))))

CN_avg_SAT <- CN_SAT %>% 
  select(CN_SAT_avg) %>% 
  mutate(CN_SAT_avg = as.numeric(CN_SAT_avg)) %>% 
  head(1)

CN_SAT_ELA <- CN_SAT %>% 
  filter(subject == "ELA")

CN_SAT_math <- CN_SAT %>% 
  filter(subject == "Math")

CN_join1 <- CN_expenditures %>% 
  full_join(CN_SAT_ELA, by = c("district" = "district"))

CN_join2 <- CN_expenditures %>% 
  full_join(CN_SAT_math, by = c("district" = "district"))

CN_join3 <- CN_SAT %>% 
  full_join(CN_teacher_demos, by = "district") 


CN_expenditures_elascore <- CN_join1 %>% 
  ggplot(aes(as.numeric(as.character(average_score_14)), as.numeric(as.character(amount)))) + geom_point(position = 'dodge') +
  theme_classic() + geom_smooth(method = 'lm') +
  labs(title = "Correlation of Connecticut's Expenditures to Score",
       subtitle = "Where Amount is total district expenditures and score is average ELA score",
       y = "Amount",
       x = "Score")

CN_expenditures_elascore

CN_expenditures_elascore %>% 
    ggsave(filename = file.path("final-proj-shiny", "connecticut_sat_ela_expenditure.png"))

CN_expenditures_mathscore <- CN_join2 %>% 
  ggplot(aes(as.numeric(as.character(average_score_14)), as.numeric(as.character(amount)))) + geom_point(position = 'dodge') +
  theme_classic() + geom_smooth(method = 'lm') +
  labs(title = "Correlation of Connecticut's Expenditures to Score",
       subtitle = "Where Amount is total district expenditures and score is average Math score",
       y = "Amount",
       x = "Score")

CN_expenditures_mathscore

CN_expenditures_mathscore %>% 
      ggsave(filename = file.path("final-proj-shiny", "connecticut_sat_math_expenditure.png"))

CN_sat_staffdemos <- CN_join3 %>% 
  filter(race == "White") %>% 
  ggplot(aes(as.numeric(as.character(percent_of_total_12)), as.numeric(as.character(average_score_14)))) + 
  geom_point(position = 'dodge') +
  geom_smooth(method = 'lm') + theme_classic() +
  labs(title = "Connecticut's Correlation of staff diversity to SAT Score",
       subtitle = "Where score is average SAT score and percent is % of white instructors",
       y = "Score",
       x = "Percent")

CN_sat_staffdemos

CN_sat_staffdemos %>% 
    ggsave(filename = file.path("final-proj-shiny", "connecticut_sat_staffdemos.png"))
```

```{r Florida}
FL_ACT <- read_excel("States/Florida/2017ACTSchool.xlsx", skip = 3) %>% 
  clean_names() %>% 
  rename(district_number = "x1",
         district_name = "x2",
         school_code = "x3",
         school_name = "x4",
         student_count = "x5")

FL_ACT <- data.frame(lapply(FL_ACT, function(x) {
                gsub('\\*', NA_character_, x)
             }))

FL_ACT <- FL_ACT %>% 
  mutate(average = mean(as.numeric(as.character(composite))))

FL_avg_act <- FL_ACT %>% 
  select(average) %>% 
  head(1)

FL_teachersalaries <- read_excel("States/Florida/1819TeacherSalaryData.xlsx", skip = 2) %>% 
  clean_names()
FL_districtsalaries <- read_excel("States/Florida/1819FLDistStSalaries.xlsx", skip = 2) %>% 
  clean_names()

FL_join1 <- FL_ACT %>% 
  full_join(FL_teachersalaries, by = "district_name")

FL_joined <- FL_join1 %>% 
  full_join(FL_districtsalaries, by = "district_name") %>% 
  select(-average) %>% 
  na.omit() 

florida_teachers <- FL_joined %>% 
  group_by(district_name) %>% 
  arrange(desc(composite)) %>% 
  ggplot(aes(x = (as.numeric(as.character(composite))), y = average_salary)) + 
  geom_point(position = 'dodge') + theme_classic() + 
  geom_smooth(method = lm, color = 'dark red') +
  labs(title = "Correlation between Florida's ACT Scores and Teacher Salaries",
       subtitle = "Where salary is average district salary and score is composite ACT score",
       y = "Salary (USD)",
       x = "Score")

florida_teachers

florida_teachers %>% 
    ggsave(filename = file.path("final-proj-shiny", "florida_teachers.png"))

florida_superintendents <- FL_joined %>% 
  arrange(desc(composite)) %>% 
  ggplot(aes(x = (as.numeric(as.character(composite))), y = (as.numeric(as.character(superintendent))))) + 
  geom_point(position = 'dodge') + theme_classic() + 
  geom_smooth(method = lm, color = 'dark red') +
  labs(title = "Correlation between Florida's ACT Scores and Superintendent Salaries",
       subtitle = "Where salary is average district salary and score is composite ACT score",
       y = "Salary (USD)",
       x = "Score")

florida_superintendents

florida_superintendents %>% 
    ggsave(filename = file.path("final-proj-shiny", "florida_superintendents.png"))

florida_school_board <- FL_joined %>% 
  arrange(desc(composite)) %>% 
  ggplot(aes(x = (as.numeric(as.character(composite))), y = (as.numeric(as.character(school_board_member))))) + 
  geom_point(position = 'dodge') + theme_classic() + 
  geom_smooth(method = lm, color = 'dark red') +
  labs(title = "Correlation between Florida's ACT Scores and School Board Salaries",
       subtitle = "Where salary is average district salary and score is composite ACT score",
       y = "Salary (USD)",
       x = "Score")

florida_school_board

florida_school_board %>% 
    ggsave(filename = file.path("final-proj-shiny", "florida_school_board.png"))
```

```{r Georgia, include = FALSE, warning = FALSE}
GA_SAT <- read_excel("States/Georgia/School Level SAT.xlsx", skip = 3,
                     col_types = c("numeric", "text",
                                      "numeric", "numeric",
                                      "numeric", "numeric")) %>% 
  rename(math = "Math Mean") %>% clean_names()
  
GA_SAT <- data.frame(lapply(GA_SAT, function(x) {
                gsub('\\*', NA_character_, x)
             })) 

GA_SAT <- na.omit(GA_SAT) %>% 
  mutate(avg_math = mean(math)) %>% 
  filter(school_name == (str_replace(school_name, "HS", "High School"))) 
  

GA_ACT <- read_excel("States/Georgia/ACT Scores School 2019.xlsx",
                     col_types = c("text","numeric","text",
                                   "numeric","numeric","numeric","numeric")) %>% 
  clean_names() %>% 
  mutate(hs_name = to_snake_case(hs_name))

GA_ACT <- data.frame(lapply(GA_ACT, function(x) {
                gsub('\\*', NA_character_, x)
             })) %>% 
  na.omit(GA_ACT) %>% 
  mutate(composite = mean(average_composite_score, na.rm = TRUE)) %>% 
        filter(hs_name == (str_replace(hs_name, "HS", "High School")))


GA_demographics <- read_csv("States/Georgia/FTE Enrollment by Race_Ethnicity and Gender Fiscal Year2020-1 Data Report.csv", skip = 4) %>% 
  clean_names() %>% 
  head(6826) %>% 
    mutate(ethnic_hispanic = 
             as.numeric(as.character(str_replace_all(ethnic_hispanic, "\\*", "0"))),
           race_american_indian = 
             as.numeric(as.character(str_replace_all(race_american_indian, "\\*", "0"))),
           race_asian = 
             as.numeric(as.character(str_replace_all(race_asian, "\\*", "0"))),
           race_black = 
             as.numeric(as.character(str_replace_all(race_black, "\\*", "0"))),
           race_pacific_islander = 
             as.numeric(as.character(str_replace_all(race_pacific_islander, "\\*", "0"))),
           race_white = 
             as.numeric(as.character(str_replace_all(race_white, "\\*", "0"))),
           two_or_more_races = 
             as.numeric(as.character(str_replace_all(two_or_more_races, "\\*", "0"))))

GA_demographics <- GA_demographics %>% 
  mutate(
           total = rowSums(GA_demographics[5:11]),
           percent_white = (race_white/total)*100)


GA_outcomes <- GA_SAT %>% 
  full_join(GA_ACT, by = c("school_name" = "hs_name")) 

```

```{r Indiana, include = F}
IN_SAT <- read_excel("States/Indiana/sat-corporation-and-school.xlsx",
                     col_types = c("text", "numeric", "text", "numeric", "numeric",
                                   "numeric", "numeric", "numeric", "numeric", "numeric")) %>% clean_names() %>% 
  mutate(percent_graduates_taking_sat = (percent_graduates_taking_sat*100)) %>% 
  filter(year == "2017-18") %>% 
  mutate(avg_composite_math_and_verbal =     
           as.numeric(avg_composite_math_and_verbal),
         avg_sat = mean(avg_composite_math_and_verbal)) %>% 
  filter(is.na(avg_composite_math_and_verbal))
  
IN_avg_sat <- IN_SAT %>% 
  select(avg_sat) %>% 
  head(1)

IN_ACT <- read_excel("States/Indiana/act-corporation-and-school.xlsx", 
                     col_types = c("text", "numeric", "text", "numeric", "numeric",
                                   "numeric", "numeric", "numeric", "numeric", "numeric", "numeric")) %>% clean_names() %>% 
  mutate(percent_graduates_taking_act = (percent_graduates_taking_act*100)) %>% 
  filter(year == "2017-18") %>% 
  mutate(IN_avg_comp = mean(as.numeric(avg_composite_score))) 

IN_avg_act <- IN_ACT %>% 
  select(IN_avg_comp) %>% 
  head(1)

IN_financial <- read_excel("States/Indiana/fy2019-school-level-financial-data-media.xlsx") %>% 
  clean_names() %>% 
  filter(str_detect(school_type, "High School")) %>% 
  mutate(avg_spending = mean(as.numeric(as.character(instructional_per_student))))

IN_avg_expenditure <- IN_financial %>% 
  select(avg_spending) %>% 
  head(1)

IN_join1 <- IN_SAT %>% 
 full_join(IN_ACT, by = c("corp_id" = "corp_no"), suffix = c("_sat", "_act")) %>% 
  group_by(corp_id) %>% 
  select(-year_sat, -corp_id, -year_act, -corp_name_act)

IN_joined <- IN_join1 %>% 
  full_join(IN_financial, by = c("corp_name_sat" = "corporation_name"))

IN_sat_spending <- IN_joined %>% 
  filter(avg_composite_math_and_verbal > 400) %>% 
  filter(instructional_per_student < 90000) %>% 
  ggplot(aes(avg_composite_math_and_verbal, instructional_per_student)) +
  geom_point() + geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Indiana's SAT Scores to Spending",
       subtitle = "Where Score is the district's average composite score and 
Amount is instructional spending per student",
       y = "Amount", 
       x = "Score")

IN_sat_spending

IN_sat_spending %>% 
    ggsave(filename = file.path("final-proj-shiny", "indiana_sat_spending.png"))

IN_act_spending <- IN_joined %>% 
  filter(instructional_per_student < 90000) %>% 
  ggplot(aes(avg_composite_score, instructional_per_student)) +
  geom_point() + geom_smooth(method = lm, color = 'dark grey', se = F) + theme_classic() +
  labs(title = "Correlation of Indiana's ACT Scores to Spending",
       subtitle = "Where Score is the district's average composite score and 
Amount is instructional spending per student",
       y = "Amount", 
       x = "Score")

IN_act_spending

IN_act_spending %>% 
    ggsave(filename = file.path("final-proj-shiny", "indiana_act_spending.png"))

```

```{r Iowa, include = F}
IO_salaries <- read_excel("States/Iowa/2019-2020 Iowa Public School Full Time Teachers_1.xlsx", skip = 13) %>% clean_names() %>%
  select(-x6, -x10, -x13, -x15, -x19, -x23, -x26, -x28, -x31, -x41, -x51) %>% 
  mutate(district_name = to_snake_case(district_name))

IO_demos <- read_excel("States/Iowa/2019-2020 Iowa Public School District PreK-12 Enrollments by District, Grade, Race and Gender.xlsx", skip = 4) %>% clean_names()

IO_ACT <- read_excel("States/Iowa/Iowa_2019_Public_Schools_Graduating_Class_5yr_trends_District level_no small Ns.xlsx", skip = 2) %>% clean_names() %>% 
  filter(grad_year == "2018") %>% 
  mutate(district_name = to_snake_case(district_name))

IO_ACT_sals <- IO_salaries %>% 
  full_join(IO_ACT, by = "district_name") 

IO_ACT_demos <- IO_ACT %>% 
  full_join(IO_demos, by = "district_name")

IO_ACT_sals <- IO_ACT_sals %>% 
  mutate(ft_teacher_teacher_leader_average_total_salary = 
           as.numeric(as.character(ft_teacher_teacher_leader_maximum_total_salary)),
         avg_comp = as.numeric(as.character(avg_comp))) 

IO_ACT_graph <- IO_ACT_sals %>% 
  ggplot(aes(avg_comp, ft_teacher_teacher_leader_average_total_salary)) +
  geom_point() 

IO_ACT_graph

```

```{r Kentucky}
KY_ACT <- read_excel("States/Kentucky/ASSESSMENT_ACT.xlsx") %>% clean_names()

KY_teacher_salaries <- read_excel("States/Kentucky/Average Classroom Teacher Salaries (1989-2020) ADA.xlsx", skip = 3) %>% clean_names() %>% select(1,2,90:91)

KY_teacher_demos <- read_excel("States/Kentucky/Classroom Teacher Ethnic-Gender Count (2020) ADA.xlsx", skip = 3) %>% clean_names() 

KY_finances <- read_excel("States/Kentucky/FINANCE.xlsx") %>% clean_names() %>% 
  filter(finance_label == c("Total Expenditures", "Total Expenditure Per Pupil", "Average Teacher Salary", "Average Principal Salary"))

KY_learning_envir <- read_excel("States/Kentucky/LEARNING_ENVIRONMENT_STUDENTS-TEACHERS.xlsx") %>% clean_names() %>% 
  filter(grade == c("Grade 09", "Grade 10", "Grade 11", "Grade 12"))

KY_admin_salaries <- read_excel("States/Kentucky/Superintendent Salaries (2001-2020) ADA.xlsx", skip = 5) %>% clean_names() %>% 
select(1,2,34,36) %>% 
  rename("school_name" = x2,
        "2018-2019" = "x2018_2019",
         "2019-2020" = "x2019_2020")

KY_join1 <- KY_ACT %>% 
  right_join(KY_teacher_salaries, by = c("dist_number" = "dist_no")) %>% 
  mutate(composite_mean_score = as.numeric(as.character(composite_mean_score)))

KY_join2 <- KY_join1 %>% 
  right_join(KY_admin_salaries, by = c("dist_number" = "district_name")) %>% 
  mutate(`2019-2020` = as.numeric(as.character(`2019-2020`))) %>% 
  filter(`2019-2020` < 250000)

KY_ACT_finance <- KY_ACT %>% 
  full_join(KY_finances, by = "cntyno") %>% 
  mutate(composite_mean_score = as.numeric(as.character(composite_mean_score)),
         finance_value = str_replace(finance_value, "\\$", "")) %>% 
  filter(disagg_label == "All Students") 

KY_join3 <- KY_join2 %>% 
  right_join(KY_finances, by = "dist_number") %>% 
  filter(finance_label == "Average Teacher Salary") 

KY_join4 <- KY_join3 %>% 
  right_join(KY_learning_envir, by = "dist_number")

KY_ACT_expenditure <- KY_join1 %>% 
  ggplot(aes(composite_mean_score, x2018_19)) + geom_point() + 
  geom_smooth(method = lm, color = "dark red") +
  labs(title = "Kentucky's Correlation of ACT Score to Expenditures",
       subtitle = "Where Score is average ACT score and Amount is district expenditures",
       y = "Amount",
       x = "Score") + theme_classic()

KY_ACT_expenditure

KY_ACT_expenditure %>% 
    ggsave(filename = file.path("final-proj-shiny", "kentucky-act-expenditure.png"))

KY_ACT_total_spending <- KY_join2 %>% 
  ggplot(aes(composite_mean_score, `2019-2020`)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Kentucky's ACT score to total expenditures",
       subtitle = "Where Amount is total district expenditures and Score is average ACT score",
       y = "Amount",
       x = "Score")

KY_ACT_total_spending

KY_ACT_teacher_filtered <- KY_ACT_finance %>% 
  filter(finance_label == "Average Teacher Salary") %>% 
  filter(!sch_name.x == "---District Total---") 

KY_ACT_teacher <- KY_ACT_teacher_filtered %>% 
  mutate(finance_value = 
           as.numeric(gsub("[\\$,]", "", KY_ACT_teacher_filtered$finance_value))) %>% 
  ggplot(aes(composite_mean_score, finance_value)) + geom_point() +
  geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Kentucky's expenditures to ACT score",
       subtitle = "Where Score is average ACT score by district
and Amount is average expenditure by district",
    y = "Amount",
    x = "Score")

KY_ACT_teacher

KY_ACT_teacher %>% 
    ggsave(filename = file.path("final-proj-shiny", "kentucky-act-teacher.png"))

KY_ACT_principal <- KY_ACT_finance %>% 
  mutate(finance_value = as.numeric(gsub(",", "", finance_value))) %>% 
  filter(finance_label == "Average Principal Salary") %>% 
  ggplot(aes(composite_mean_score, finance_value)) + geom_point() +
  geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Kentucky's ACT scores to financial value",
       subtitle = "Where Score is average ACT score and Amount is financial investment",
       y = "Amount", 
       x = "Score")

KY_ACT_principal

KY_ACT_principal %>% 
    ggsave(filename = file.path("final-proj-shiny", "kentucky-act-principal.png"))
```

```{r Louisiana}
LA_teacher_salaries <- read_excel("States/Louisiana/2018-2019-actual-public-classroom-teacher-salary-averages-by-school-district.xlsx", skip = 6) %>% clean_names() 
LA_teacher_salaries <- LA_teacher_salaries[-c(1,3), ] 

LA_ACT <- read_excel("States/Louisiana/act-scores-class-of-2019.xlsx", skip = 4) %>% 
  clean_names()

LA_joined <- LA_ACT %>% 
  full_join(LA_teacher_salaries, by = c("district" = "lea_name")) %>% 
  rename(average_composite_score = x2018_2019_average_composite_score) %>% 
  mutate(average_composite_score = as.numeric(average_composite_score)) %>% 
  filter(average_composite_score >15)

LA_ACT_teacher <- LA_joined %>% 
  ggplot(aes(average_composite_score, avg_classroom_teachers_salary_without_extra_compensation_7)) +
  geom_point() + geom_smooth(method = lm) +
  theme_classic() +
  labs(title = "Correlation of Louisiana's ACT score to teacher salary",
       subtitle = "Where Score is average ACT score and Amount is average teacher salary",
       y = "Amount",
       x = "Score")

LA_ACT_teacher
```

```{r Massachusetts}
MA_SAT_18_19 <- read_excel("States/Massachusetts/sat_performance.xlsx", 
                        col_types = c("text", "numeric",
                                      "numeric", "numeric",
                                      "logical", "numeric"),
                        skip = 1) %>% 
  clean_names() %>% 
  mutate(avg_reading = 
          mean(reading_writing, na.rm = TRUE),
         avg_math =
           mean(math, na.rm = TRUE)) 

MA_PPE_18 <- read_excel("States/Massachusetts/PerPupilExpenditures.xlsx",
                        col_types = c("text", "numeric",
                                      "numeric", "text",
                                      "text", "text",
                                      "text", "text",
                                      "logical"),
                        skip = 1) %>% 
  clean_names() %>% 
  select(-x9)

mass_staff_demographics <- read_excel("States/Massachusetts/staffracegender.xlsx",
                                      skip = 1) %>% 
  clean_names()

mass_salaries <- read_excel("States/Massachusetts/TeacherSalaries.xlsx", skip = 1) %>% 
  clean_names()

MA_join1 <- MA_SAT_18_19 %>% 
  full_join(MA_PPE_18, by = c("district_name" = "district_name",
                              "district_code" = "district_code"))

MA_join2 <- MA_SAT_18_19 %>% 
  full_join(mass_staff_demographics, by = c("district_name" = "district_school_name")) %>% 
  mutate(african_american_number = as.numeric(as.character(african_american_number)),
         asian_number = as.numeric(as.character(asian_number)),
         hispanic_number = as.numeric(as.character(hispanic_number)),
         white_number = as.numeric(as.character(white_number)),
         native_american_number = as.numeric(as.character(native_american_number)),
         native_hawaiian_pacific_islander_number = as.numeric(as.character(native_hawaiian_pacific_islander_number)),
         multi_race_non_hispanic_number =
           as.numeric(as.character(multi_race_non_hispanic_number)))

MA_join2 <- MA_join2 %>% 
  mutate(
        total = rowSums(MA_join2[10:16]),
        percent_white = ((white_number/total)*100))

MA_SAT_PPE_math <- MA_join1 %>% 
  mutate(total_expenditures_per_pupil = 
           as.numeric(gsub("[\\$,]", "", MA_join1$total_expenditures_per_pupil))) %>% 
  ggplot(aes(math, total_expenditures_per_pupil)) + geom_point() +
  geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Massachusetts' expenditures per pupil to SAT score",
       subtitle = "Where Amount is per pupil expenditure and Score is average SAT score",
       y = "Amount",
       x = "Score")

MA_SAT_PPE_math

MA_SAT_PPE_math %>% 
    ggsave(filename = file.path("final-proj-shiny", "mass-sat-ppe-math.png"))

MA_SAT_PPE_reading <- MA_join1 %>% 
  mutate(total_expenditures_per_pupil = 
           as.numeric(gsub("[\\$,]", "", MA_join1$total_expenditures_per_pupil))) %>% 
  ggplot(aes(reading_writing, total_expenditures_per_pupil)) + geom_point() +
  geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Massachusetts' expenditures per pupil to SAT score",
       subtitle = "Where Amount is per pupil expenditures and Score is average SAT reading score",
       y = "Amount",
       x = "Score")

MA_SAT_PPE_reading

MA_SAT_PPE_reading %>% 
    ggsave(filename = file.path("final-proj-shiny", "mass-sat-ppe-reading.png"))

MA_SAT_demos_reading <- MA_join2 %>% 
  filter(percent_white > 35) %>% 
  ggplot(aes(percent_white, reading_writing)) + geom_point() + 
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Massachusetts' demographics to reading SAT scores",
       subtitle = "Where Score is average SAT reading score and Percent is percent of white students",
       x = "Percent",
       y = "Score")

MA_SAT_demos_reading

MA_SAT_demos_reading %>%     
  ggsave(filename = file.path("final-proj-shiny", "mass-sat-demos-reading.png"))


MA_SAT_demos_math <- MA_join2 %>% 
  filter(percent_white > 35) %>% 
  ggplot(aes(percent_white, math)) + geom_point() + 
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Massachusetts' demographics to math SAT scores",
       subtitle = "Where Score is average SAT math score and Percent is percent of white students",
       x = "Percent",
       y = "Score")

MA_SAT_demos_math

MA_SAT_demos_math %>%     
  ggsave(filename = file.path("final-proj-shiny", "mass-sat-demos-math.png"))


MA_SAT_sals <- MA_SAT_18_19 %>% 
  select(-writing) %>% 
  full_join(mass_salaries, by = "district_name") %>% 
  na.omit(MA_SAT_18_19) %>% 
  mutate(average_salary = str_replace(average_salary, "\\$", ""),
         average_salary = as.numeric(str_replace(average_salary, ",", "")))

MA_SAT_sals_reading <- MA_SAT_sals %>% 
  ggplot(aes(reading_writing, average_salary)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Massachusetts' teacher salaries to SAT reading score",
       subtitle = "Where Amount is average teacher salary and Score is SAT reading score",
       y = "Amount",
       x = "Score")
  
MA_SAT_sals_reading

MA_SAT_sals_reading %>% 
    ggsave(filename = file.path("final-proj-shiny", "mass-sat-sals-reading.png"))

MA_SAT_sals_math <- MA_SAT_sals %>% 
  ggplot(aes(math, average_salary)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Massachusetts' teacher salaries to SAT math score",
       subtitle = "Where Amount is average teacher salary and Score is SAT math score",
       y = "Amount",
       x = "Score")
  

MA_SAT_sals_math

MA_SAT_sals_math %>% 
    ggsave(filename = file.path("final-proj-shiny", "mass-sat-sals-math.png"))
```

```{r Nevada}
NV_outcomes <- read_excel("States/Nevada/Nevada Outcomes.xlsx") %>% clean_names() %>% 
  rename(district_name = group) 

NV_demographics <- read_excel("States/Nevada/Nevada Demos.xlsx") %>% clean_names() %>% 
  rename(district_name = name) 

NV_financial <- read_excel("States/Nevada/Nevada Financials.xlsx") %>% clean_names() %>% 
  rename(district_name = name)

NV_join1 <- NV_outcomes %>% 
  full_join(NV_demographics, by = "district_name")

NV_joined <- NV_join1 %>% 
  full_join(NV_financial, by = "district_name")

NV_demo_outcomes <- NV_joined %>% 
  ggplot(aes(white_percent, reading_percent_meets_standard)) +
  geom_point() + geom_smooth(method = lm) +
  theme_classic() + 
  labs(title = "Correlation of Nevada's demographics to percent of students 
meeting reading standards",
       subtitle = "Where Benchmark is percent meeting reading standard and Percent is percent of white students",
       y = "Benchmark",
       x = "Percent")

NV_demo_outcomes

NV_demo_outcomes %>%     
  ggsave(filename = file.path("final-proj-shiny", "nv-demo-outcomes.png"))


NV_financial_outcomes <- NV_joined %>% 
  ggplot(aes(instruction_percent, reading_percent_meets_standard)) +
  geom_point() + geom_smooth(method = lm) +
  theme_classic() +
  labs(title = "Correlation of Nevada's instruction percent to students 
meeting reading benchmark",
       subtitle = "Where Benchmark is percent meeting reading standard 
and Percent is percent of instruction spending",
       y = "Benchmark",
       x = "Percent")

NV_financial_outcomes

NV_financial_outcomes %>% 
    ggsave(filename = file.path("final-proj-shiny", "nv-financial-outcomes.png"))
```

```{r Oklahoma}
OK_ACT <- read_excel("States/Oklahoma/District level_ACT_2016_Senior.xlsx") %>% 
  clean_names()

OK_staff <- read_excel("States/Oklahoma/CertStaff_SPR-FY1920_2020-03-12-MidYr.xlsx", skip = 1) %>% clean_names() 

OK_teachers <- OK_staff %>% 
  filter(jobcode == "210") %>% 
  filter(jobdesc == "TEACHER") %>% 
  filter(degree == "4") %>% 
  filter(race == "5") %>% 
  filter(fte == "1") %>% 
  filter(str_detect(subject_desc, "ELEM") == FALSE) %>% 
  filter(gender == "M") %>% 
  filter(subject_desc == "MATHEMATICS" | subject_desc == "SCIENCE" | 
           subject_desc == "SOCIAL STUDIES" | subject_desc == "MUSIC") 

OK_supt <- OK_staff %>% 
  filter(jobcode == "115") %>% 
  mutate(co = as.numeric(as.character(co)))

OK_ACT_staff <- OK_ACT %>% 
  inner_join(OK_staff, by = "district_name") %>% 
  filter(jobdesc == "TEACHER") %>% 
  filter(degree == "4") %>% 
  filter(race == "5") %>% 
  filter(fte == "1") %>% 
  filter(str_detect(subject_desc, "ELEM") == FALSE) %>% 
  filter(gender == "M") %>% 
  filter(subject_desc == "MATHEMATICS" | subject_desc == "SCIENCE" | 
           subject_desc == "SOCIAL STUDIES" | subject_desc == "MUSIC") %>% 
  mutate(composite = as.numeric(as.character(composite)))

OK_ACT_staff_graph <- OK_ACT_staff %>% 
  ggplot(aes(composite, base_salary, color = subject_desc)) + geom_point() +
  geom_smooth(method = lm, se = F) +
  theme_classic() +
  labs(title = "Correlation of Oklahoma's teacher salaries and ACT score",
       subtitle = "Where Amount is average teacher salary and Score is average ACT score",
       y = "Amount", 
       x = "Score")

OK_ACT_staff_graph

OK_ACT_staff_graph %>% 
    ggsave(filename = file.path("final-proj-shiny", "ok-act-staff.png"))

OK_ACT_teachers <- OK_ACT %>% 
  full_join(OK_teachers, by = "county_name")

OK_ACT_supt <- OK_ACT %>% 
  full_join(OK_supt, by = c("countycode" = "co")) %>% 
  filter(!school_name == "DISTRICT WIDE SERVICES") %>% 
  mutate(composite = as.numeric(as.character(composite))) %>% 
  ggplot(aes(composite, base_salary)) + geom_point() +
  geom_smooth(method = lm, color = 'dark red') + theme_classic() +
  labs(title = "Correlation of Oklahoma's superintendent salaries to ACT score",
       subtitle = "Where Amount is average superintendent salary and Score is average ACT score",
       y = "Amount",
       x = "Score")

OK_ACT_supt

OK_ACT_supt %>% 
    ggsave(filename = file.path("final-proj-shiny", "ok-act-supt.png"))
```

```{r Pennsylvania}
PA_grad_rate <- read_excel("States/Pennsylvania/PA Grad Rates.xlsx") %>% clean_names()

PA_ACT <- read_excel("States/Pennsylvania/2019 ACT Scores for Public Schools.xlsx", skip = 7) %>%
  clean_names()

PA_SAT <- read_excel("States/Pennsylvania/2019 SAT Scores for Public Schools.xlsx", skip = 5) %>%
  clean_names()

PA_outcomes <- PA_ACT %>% 
  left_join(PA_SAT, by = "school_name")

PA_joined <- PA_outcomes %>% 
  right_join(PA_grad_rate, by = c("school_name" = "school")) %>% 
  select(-migrant_grad_rate, -el_grad_rate) %>% 
  mutate(composite_score_average = as.numeric(as.character(composite_score_average)),
         cohort_grad_rate = (cohort_grad_rate*100))

PA_ACT_grad <- PA_joined %>% 
  ggplot(aes(composite_score_average, cohort_grad_rate)) + geom_point() +
  geom_smooth(method = 'lm') + theme_classic() +
  labs(title = "Correlation of Pennsylvania's ACT score to graduation rate",
       subtitle = "Where Score is average ACT score and Percent is percent of graduation",
       y = "Percent",
       x = "Score") +
  ylim(0, 100)

PA_ACT_grad

PA_ACT_grad %>% 
   ggsave(filename = file.path("final-proj-shiny", "pa-grad-rate.png"))
```

```{r South Carolina}
SC_ACT <- read_excel("States/South Carolina/SAT2019_Schoolsfinal.xlsx", skip = 2) %>% 
  clean_names()
SC_SAT <- read_excel("States/South Carolina/ACT-Schools2019.xlsx", skip = 1) %>% 
  clean_names()

SC_expenditures <- read_excel("States/South Carolina/Expenditure FY 2017-2018.xlsx", skip = 2)%>%
  clean_names() 

SC_expenditures <- SC_expenditures[-c(1,2,7:140), -1] %>% 
  rename(program = x2) %>% 
  pivot_longer(cols = (2:102), names_to = "district_name", values_to = "amount") 

SC_teacher_demos <- read_excel("States/South Carolina/SOUTH CAROLINA TEACHERS BY RACE AND GENDER 2015-16.xlsx")  %>% 
  clean_names() %>% 
  mutate(district = to_snake_case(district)) 

SC_outcomes <- SC_ACT %>% 
  right_join(SC_SAT, by = "school_id") %>% 
  mutate(district_name = to_snake_case(district_name)) 

SC_join1 <- SC_outcomes %>% 
  full_join(SC_teacher_demos, by = c("district_name" = "district"))

SC_joined <- SC_join1 %>% 
  full_join(SC_expenditures, by = "district_name") %>% 
  mutate(total_score = as.numeric(as.character(total_score)),
         mean_composite_score = as.numeric(as.character(mean_composite_score))) %>% 
  filter(!mean_composite_score == "0")

SC_joined <- SC_joined %>% 
  mutate(white_total = rowSums(SC_joined[20:23]),
         percent_white = ((white_total/total_staff)*100)) %>% 
  tail(290)

SC_SAT_financial <- SC_joined %>% 
  na.omit() %>% 
  ggplot(aes(total_score, amount)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of South Carolina's SAT score to school district expenditures",
       subtitle = "Where Amount is school's expenditures and Score is SAT score",
       y = "Amount",
       x = "Score")

SC_SAT_financial %>% 
     ggsave(filename = file.path("final-proj-shiny", "sc-sat-financial.png"))

SC_ACT_financial <- SC_joined %>% 
  na.omit() %>% 
  ggplot(aes(mean_composite_score, amount)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of South Carolina's ACT score to school district expenditures",
       subtitle = "Where Amount is school's expenditures and Score is ACT score",
       y = "Amount",
       x = "Score")

SC_ACT_financial %>% 
    ggsave(filename = file.path("final-proj-shiny", "sc-act-financial.png"))

SC_SAT_demos <- SC_joined %>% 
  ggplot(aes(total_score, percent_white)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of South Carolina's SAT score to percent of white students",
       subtitle = "Where Score is average SAT score and Percent is percent of the student
body that is white",
    y = "Percent",
    x = "Score") +
  ylim(25,100)

SC_SAT_demos %>% 
      ggsave(filename = file.path("final-proj-shiny", "sc-sat-demos.png"))


SC_ACT_demos <- SC_joined %>% 
  ggplot(aes(mean_composite_score, percent_white)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of South Carolina's ACT score to percent of white students",
       subtitle = "Where Score is average ACT score and Percent is percent of the student
body that is white",
    y = "Percent",
    x = "Score") +
  ylim(25,100)
 
SC_ACT_demos %>% 
        ggsave(filename = file.path("final-proj-shiny", "sc-act-demos.png"))

```

```{r South Dakota}
SD_all <- read_excel("States/South Dakota/19-Profile3.xlsx", skip = 4) %>% 
  clean_names()

SD_all <- SD_all[ , -c(3:5, 11:53, 171:220)]

SD_all <- SD_all[ , -c(8:38, 40:67, 70)]

SD_all_financials <- SD_all[ , -c(23,24,25:64)]

SD_ACT <- read_excel("States/South Dakota/SD ACT.xlsx") %>% clean_names()

SD_joined <- SD_all_financials %>% 
  full_join(SD_ACT, by = "district_name") 

SD_joined %>% 
  group_by(district_name) %>% 
  ggplot(aes(act_composite_score, average_teacher_salary)) + geom_point() +
  theme_classic() + geom_smooth(method = lm, color = 'dark red') +
  labs(title = "Correlation of South Dakota's ACT Scores to Teacher Salaries",
       subtitle = "Where Score is Average ACT Score and Salary is the district's average salary",
       y = "Salary (USD)",
       x = "Score")

SD_ACT_stsr <- SD_joined %>% 
  ggplot(aes(act_composite_score, student_to_staff_ratio)) + geom_point() +
  geom_smooth(method = lm) +
  theme_classic() +
  labs(title = "Correlation of South Dakota's ACT score to ratio",
       subtitle = "Where Ratio is ratio of students to staff and Score is average ACT score",
       y = "Ratio",
       x = "Score")

SD_ACT_stsr %>% 
    ggsave(filename = file.path("final-proj-shiny", "sd-act-stsr.png"))

```

```{r Tennessee}
TN_ACT <- read_excel("States/Tennessee/ACT_district_suppressed_2019.xlsx") %>% 
  clean_names()

TN_demos <- read_excel("States/Tennessee/district_profile_2017-18.xlsx") %>% 
  clean_names()

TN_joined <- TN_ACT %>% 
  full_join(TN_demos, by = "district") %>% 
  mutate(average_composite_score = as.numeric(as.character(average_composite_score)))

TN_ACT_demos <- TN_joined %>% 
  ggplot(aes(average_composite_score, white_pct)) + geom_point() +
  geom_smooth(method = lm) + theme_classic() +
  labs(title = "Correlation of Tennessee's ACT scores to percent of white students",
       subtitle = "Where Score is average ACT score and Percent is percent of the student
body that is white",
    y = "Percent",
    x = "Score") +
  ylim(0,100)

TN_ACT_demos %>% 
      ggsave(filename = file.path("final-proj-shiny", "tn-act-demos.png"))

TN_ACT_expenditures <- TN_joined %>% 
  mutate(per_pupil_expenditures_per_ada =
           as.numeric(as.character(per_pupil_expenditures_per_ada))) %>% 
  ggplot(aes(average_composite_score, per_pupil_expenditures_per_ada)) +
  geom_point() + geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Tennessee's ACT scores to expenditures",
       subtitle = "Where Score is average ACT score and Amount is expenditures",
       y = "Amount",
       x = "Score") +
  ylim(7500,13500)

TN_ACT_expenditures %>% 
        ggsave(filename = file.path("final-proj-shiny", "tn-act-expenditures.png"))


TN_demos_expenditures <- TN_joined %>% 
  mutate(per_pupil_expenditures_per_ada =
           as.numeric(as.character(per_pupil_expenditures_per_ada))) %>% 
  ggplot(aes(white_pct, per_pupil_expenditures_per_ada)) +
  geom_point() + geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Tennessee's demographics to expenditures",
       subtitle = "Where Amount is district per pupil expenditures and Percent is percent
of the student body that is white",
      y = "Amount",
      x = "Percent") +
  ylim(7500,13500)

TN_demos_expenditures %>% 
          ggsave(filename = file.path("final-proj-shiny", "tn-demos-expenditures.png"))

```

```{r Texas}
TX_ACT <- read_csv("States/Texas/act_district_data_class_2017.csv") %>% 
  clean_names()
TX_ACT <- na.omit(TX_ACT)

TX_SAT <- read_csv("States/Texas/sat_district_data_class_2017.csv") %>% 
  clean_names() 
TX_SAT <- na.omit(TX_SAT) 

TX_financial <- read_excel("States/Texas/Total Operating Expenditures 2006-2017.xlsx", skip = 1) %>% 
  clean_names() %>% 
  select(1,2,36:38) 

TX_outcomes <- TX_ACT %>% 
  full_join(TX_SAT, by = "district", suffix = c("_act", "_sat")) %>% 
    mutate_each(funs(str_replace_all(., "\"", ""))) %>% 
    mutate_each(funs(str_replace_all(., "=", "")))

TX_joined <- TX_outcomes %>% 
  full_join(TX_financial, by = c("district" = "cdn"))

TX_ACT_financial <- TX_joined %>% 
  mutate(compos = as.numeric(as.character(compos)),
         all_funds_operating_expenditures_per_student_38 = 
           as.numeric(as.character(all_funds_operating_expenditures_per_student_38))) %>% 
  ggplot(aes(compos, all_funds_operating_expenditures_per_student_38)) +
  geom_point() + geom_smooth(method = lm, color = 'dark red') +
  theme_classic() + 
  labs(title = "Correlation of Texas' ACT scores to district expenditures",
       subtitle = "Where Score is average ACT score and Amount is average district expenditures",
       y = "Amount",
       x = "Score") +
  ylim(5000,32500)

TX_ACT_financial %>% 
            ggsave(filename = file.path("final-proj-shiny", "tx-act-financial.png"))


TX_SAT_financial <- TX_joined %>% 
  mutate(total = as.numeric(as.character(total)),
         all_funds_operating_expenditures_per_student_38 = 
           as.numeric(as.character(all_funds_operating_expenditures_per_student_38))) %>% 
  ggplot(aes(total, all_funds_operating_expenditures_per_student_38, 
             color = region_sat)) +
  geom_point(position = 'dodge', alpha = 0.01) + geom_smooth(method = 'lm') +
  theme_classic() +
  labs(title = "Correlation of Texas' SAT scores to expenditures",
       subtitle = "Where Score is average SAT scores and Amount is district expenditures",
       y = "Amount",
       x = "Score") +
  ylim(5000,32500) +
  theme(legend.position = "none")

TX_SAT_financial %>% 
    ggsave(filename = file.path("final-proj-shiny", "tx-sat-financial.png"))

```

```{r Wisconsin}
WI_ACT <- read_excel("States/Wisconsin/Wisconsin ACT.xlsx") %>% clean_names() %>% 
  rename(district_name = district) 

WI_financial <- read_csv("States/Wisconsin/2017-2018-12-Budget-Data-AtoZ-with-Rollups.csv") %>% 
  clean_names() 

WI_joined <- WI_ACT %>% 
  full_join(WI_financial, by = "district_name")

WI_ACT_financial <- WI_joined %>% 
  mutate(amount = as.numeric(as.character(amount)),
         district_nmbr = as.numeric(as.character(district_nmbr))) %>% 
  select(-coa_act) %>% 
  group_by(school) %>% 
  sample_n(size = 1)

WI_ACT_financial <- WI_ACT_financial %>% 
  filter(amount < 1000000) %>% 
  filter(!amount == "0") %>% 
ggplot(aes(composite, amount)) + geom_point() +
  geom_smooth(method = lm, color = 'dark red') +
  theme_classic() +
  labs(title = "Correlation of Wisconsin's ACT score to expenditures",
       subtitle = "Where Score is average ACT score and Amount is expenditures by district",
       y = "Amount",
       x = "Score")

WI_ACT_financial %>% 
      ggsave(filename = file.path("final-proj-shiny", "wi-act-financial.png"))

```

```{r Wyoming}
WY_staff_salaries <- read_csv("States/Wyoming/DistrictVersionAllStaffByCategoryWithAverageSalaries.csv") %>% clean_names() %>% 
  select(1:7) %>% 
  rename(district_name = "district_name1")

WY_ACT <- read_excel("States/Wyoming/WY ACT.xlsx", skip = 1) %>% clean_names() 

WY_joined <- WY_ACT %>% 
  full_join(WY_staff_salaries, by = "district_name") %>% 
  na.omit(WY_joined) %>% 
  filter(group_name == "Teachers Total") %>% 
  mutate(average_total_salary = str_replace(average_total_salary, "\\$", ""),
         average_total_salary = as.numeric(str_replace(average_total_salary, ",", "")))

WY_ACT_salary <- WY_joined %>% 
  ggplot(aes(average_17, average_total_salary)) + geom_point() +
  theme_classic() + geom_smooth(method = lm) +
  labs(title = "Correlation of Wyoming's ACT score to Teacher salary",
       subtitle = "Where Score is average ACT score and Amount is average teacher salary",
       y = "Amount",
       x = "Score")

WY_ACT_salary %>% 
    ggsave(filename = file.path("final-proj-shiny", "wy-act-salary.png"))
```

```{r averages, include = F}
act_averages <- c(FL_avg_act, IN_avg_act)
sat_averages <- c(CN_avg_SAT, IN_avg_sat)
teacher_sals_averages <- c(1,2,3)
expenditure_averages <- c(CN_avg_expenditure, IN_avg_expenditure)
states <- c("Connecticut", "Indiana") 

fake_expenditures <- c(30000, 45000, 28000, 35000, 37000,
                       27000, 40000, 41000, 32000, 33500)
fake_sat <- c(1030, 904, 805, 934, 852, 1032, 963, 854, 702, 989)
fake_act <- c(23, 28, 30, 26, 28, 31, 24, 25.5, 28.3, 30.1)
fake_state <- c("Indiana", "Connecticut", "Georgia",
                "South Dakota", "Idaho", "Nevada",
                "Maine", "Rhode Island", "New York", "Florida")

fake_state_tibble <- tibble(fake_state, fake_sat, fake_act, fake_expenditures)

states_averages <- tibble(states, expenditure_averages, sat_averages)

states_averages %>% 
  mutate(sat_averages = as.numeric(as.character(sat_averages)),
         states = as.character(states),
         expenditure_averages = as.numeric(as.character(expenditure_averages)))

fake_states_groupings <- fake_state_tibble %>% 
  rename(State = fake_state) %>% 
  ggplot(aes(fake_act, fake_expenditures, color = State)) + geom_point() +
  geom_smooth(method = lm, se = F, color = 'dark red') + theme_classic() +
  labs(title = "Correlation of America's average ACT score to average expenditures",
       subtitle = "Where Amount is average school expenditures by state and
Score is average ACT score by state",
      y = "Amount",
      x = "Score") +
  theme(legend.position = "right")

fake_states_groupings %>% 
    ggsave(filename = file.path("final-proj-shiny", "fake-correlations.png"))

```

URL for my Shiny app: https://garrett-rolph.shinyapps.io/final-proj-shiny/
